/**
 * P1 "honest short-game review": identifying the opening family/variation
 * a real game actually reached, and offering a real, textbook strategic
 * idea for it when one is available — never a fabricated claim about
 * what this specific learner did right or wrong. Deliberately
 * conservative: an opening is only ever named when the played SAN
 * sequence is an exact prefix match against a known line (the longest
 * one that matches, so a specific variation is preferred over its parent
 * family when both apply) — no fuzzy or partial matching, so a genuinely
 * unrecognized sequence returns nothing rather than a guess.
 *
 * The move-name/ECO data itself comes from the real CC0
 * lichess-org/chess-openings dataset (see
 * docs/content-sources.md/`packages/content/openings/chess-openings.json`,
 * generated by scripts/import-chess-openings.ts) — 2,337 lines, each
 * chess-rules-verified legal, capped at 10 plies so this never becomes
 * the "memorization of long forced lines for beginners" the founding
 * brief explicitly warns against.
 *
 * The per-opening strategic `idea` text is NOT part of that dataset (the
 * CC0 set only has eco/name/move-facts, no prose) — it's original
 * MoveWise writing, curated for a modest set of the most common openings
 * a beginner/intermediate learner will actually reach. An identified
 * opening outside that curated set still gets an accurate name (backed
 * by real, licensed data) but an empty `idea` — never a fabricated
 * strategic claim for an opening nobody has actually written about here.
 */
import openingsData from "../../../packages/content/openings/chess-openings.json";

interface OpeningEntry {
  eco: string;
  name: string;
  sanMoves: string[];
}

const OPENING_BOOK = openingsData as OpeningEntry[];

// Original MoveWise prose, keyed by the CC0 dataset's own base family name
// (the part before ":") — never copied from any external source. Deliberately
// small: only openings common enough in real beginner/intermediate games to
// be worth a hand-written strategic note.
const IDEA_BY_BASE_NAME: Record<string, string> = {
  "Ruy Lopez":
    "White typically follows up with O-O and re-routing the bishop toward b3, building long-term pressure on e5 rather than an immediate attack.",
  "Italian Game": "A common follow-up is c3 and d4, building a strong pawn center before castling.",
  "Scotch Game": "White opens the center immediately, trading a central pawn for faster piece activity.",
  "Vienna Game": "White develops the knight before committing the f-pawn, keeping the option of a later f4 open.",
  "King's Gambit": "White offers a pawn early for rapid development and open lines toward Black's king.",
  "Sicilian Defense":
    "Black fights for the center asymmetrically rather than meeting e4 with ...e5 — the resulting positions are usually sharper for both sides.",
  "French Defense":
    "The position often becomes closed early — piece activity behind the pawn chain matters more than a quick attack.",
  "Caro-Kann Defense":
    "Black keeps a solid pawn structure while still contesting the center with a soon-to-follow ...d5.",
  "Scandinavian Defense":
    "Black regains the pawn quickly (often ...Qxd5), then focuses on fast, safe development rather than holding the extra pawn.",
  "Pirc Defense": "Black delays central pawn moves, planning to challenge White's center with pieces first.",
  "Alekhine Defense":
    "Black invites White's pawns forward, planning to attack the resulting overextended center later.",
  "Queen's Gambit": "White offers a wing pawn to gain central control and faster development, not to keep the pawn.",
  "King's Indian Defense":
    "Black lets White build a big center, planning a later ...e5 or ...c5 break to challenge it.",
  "London System":
    "A solid, repeatable setup — the same piece placement works against many different Black replies.",
  "English Opening": "A flexible flank opening — the center is contested indirectly rather than occupied immediately.",
};

export interface IdentifiedOpening {
  name: string;
  eco: string;
  /** Original MoveWise strategic note, or "" when this specific opening isn't in the curated idea set yet — never a fabricated claim. */
  idea: string;
}

function baseFamilyName(fullName: string): string {
  return fullName.split(":")[0]!.trim();
}

/**
 * Exact-prefix match only — the longest matching entry wins, so a more
 * specific variation is preferred over its parent family whenever the
 * played moves actually support it. `sanMoves` is every SAN move
 * actually played, in order, both colors interleaved (i.e.
 * `review.moves.map(m => m.playedMove)`).
 */
export function identifyOpening(sanMoves: string[]): IdentifiedOpening | null {
  let best: OpeningEntry | null = null;
  for (const entry of OPENING_BOOK) {
    if (entry.sanMoves.length > sanMoves.length) continue;
    const isPrefix = entry.sanMoves.every((san, i) => sanMoves[i] === san);
    if (isPrefix && (!best || entry.sanMoves.length > best.sanMoves.length)) best = entry;
  }
  if (!best) return null;
  return { name: best.name, eco: best.eco, idea: IDEA_BY_BASE_NAME[baseFamilyName(best.name)] ?? "" };
}
